/*DROP TABLE IF EXISTS tb_unidade CASCADE;*/

CREATE TABLE tb_unidade(
    unidade_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    nome VARCHAR(255) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    cozinha_completa BOOLEAN NOT NULL DEFAULT TRUE
);